### ISSUE TITLE
Optware-ng on android armv7

### ISSUE THREAD

**Issue by armando-basile** [alllexx88/Optware-ng#6] opened 2015-09-01 14:01 UTC
Hi, i installed old optware on my android box AmLogic s812 but i saw that optware-ng have more updated packages, so i would like to install it on my android box.
Could it's possible ?

thanks
Armando

**Comment by alllexx88** [comment] 2015-09-01 14:41
Hi, it should be possible, running this command
```
wget -O - http://optware-ng.zyxmon.org/buildroot-armeabi/buildroot-armeabi-bootstrap.sh | sh
```
as root should work, as long as `/opt` is writable and you have `wget`, `tar` with gzip and `echo` commands. These should be there, but anyway it's better to install `busybox` on your box if it's not already installed, since some post install scripts may require some additional commands

Regards,

**Comment by armando-basile** [comment] 2015-09-01 17:21
Hi Alex,
seems that installation done, i saw help message if i do:
/opt/bin/ipkg

but if i try to /opt/bin/ipkg update i receive
root@s806:/opt/bin # /opt/bin/ipkg update                                             
mkdtemp: No such file or directory

**Comment by alllexx88** [comment] 2015-09-01 17:44
Hmm, looks like mkdtemp() function errors out, since there's no `/tmp` directory on your device, which is expected to be on UNIX, but probably usually isn't there in android. Can you try this?

```
mkdir -p /sdcard/tmp
TMPDIR=/sdcard/tmp /opt/bin/ipkg update
```

**Comment by armando-basile** [comment] 2015-09-01 18:10
i solved fixing temp folder i installed /opt under /data, so i launch a script at boot to reset environment:

```
#!/system/bin/sh
mount -o rw,remount rootfs /
ln -s /data/opt /opt
mkdir -p /tmp
ln -s /data/opt/tmp /tmp
mkdir -p /bin
ln -s /system/bin/sh /bin/sh
mount -o ro,remount /
```

**Comment by armando-basile** [comment] 2015-09-01 19:58
i installed and configured minidlna and transmission without init.d scripts but adding into start.sh script launch:
```
#!/system/bin/sh

# remount filesystem
mount -o rw,remount rootfs /
ln -s /data/opt /opt
mkdir -p /tmp
ln -s /data/opt/tmp /tmp
mkdir -p /bin
ln -s /system/bin/sh /bin/sh
mount -o ro,remount /
sleep 2

export PATH=$PATH:/data/opt/sbin:/data/opt/bin:/data/opt:/bin:/system/bin
export TMPDIR=/data/opt/tmp

# transmission daemon
rm -rf /opt/var/run/transmission-daemon.pid
/data/opt/bin/transmission-daemon -g /data/opt/etc/transmission-daemon -e /data/opt/var/log/transmission-daemon.log --log-error

# minidlna server
rm -rf /data/opt/var/minidlna/minidlna.pid
(/data/opt/sbin/minidlnad -f /data/opt/etc/minidlna.conf -P /data/opt/var/minidlna/minidlna.pid -d >/opt/etc/minidlna/minidlna.log) &

```

i would like also to configure dropbear to use ssh, so i installed and ssh root@android_ip show me login + password request but i don't know which is root password. I think that should create /opt/etc/passwd file ???

**Comment by alllexx88** [comment] 2015-09-02 05:20
I'm glad `minidlna` and `transmission` are working for you. As for `dropbear`, it's using system authentication (passwords hashes are usually in `/etc/shadow`), so if you don't know `root`'s password and can't change it, you can try public key authentication. Look at [this](http://wiki.openwrt.org/doc/howto/dropbear.public-key.auth) OpenWrt guide (skip the Disable password login part), just use `/opt/etc/dropbear` instead of `/etc/dropbear`.

**Comment by alllexx88** [comment] 2015-09-02 05:32
BTW, you might also want to either mount RAM disk on `/tmp` or clean up `/data/opt/tmp` on boot, since it can often contain garbage that some user programs 'forgot' to clean

**Comment by armando-basile** [comment] 2015-09-03 20:20
other little issue: with some installed packages i saw always:
```link failed No such file or directory```
at the end of opkg install. Parsing control.tar.gz into package i saw that problem is command
```
/opt/bin/update-alternatives --install /opt/bin/bzip2 bzip2 /opt/bin/bzip2-bzip2 80
```
that return this message. I already created folder /opt/var/lib/alternatives, should create some other folder ?

**Comment by alllexx88** [comment] 2015-09-04 10:49
I can't reproduce this. You can use `strace` to tackle that down:

```
/opt/bin/ipkg update
/opt/bin/ipkg install strace
/opt/bin/strace /opt/bin/update-alternatives --install /opt/bin/bzip2 bzip2 /opt/bin/bzip2-bzip2 80 2>&1 | grep "No such file or directory"
```

This should show all failed attempts to access a file/dir, e.g.

```
/opt/bin/strace /opt/bin/update-alternatives --install /opt/bin/bzip2 bzip2 /opt/bin/bzip2-bzip2 80 2>&1 | grep "No such file or directory"
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY)      = -1 ENOENT (No such file or directory)
open("/lib/tls/i686/sse2/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/tls/i686/sse2", 0xffb76808) = -1 ENOENT (No such file or directory)
open("/lib/tls/i686/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/tls/i686", 0xffb76808)     = -1 ENOENT (No such file or directory)
open("/lib/tls/sse2/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/tls/sse2", 0xffb76808)     = -1 ENOENT (No such file or directory)
open("/lib/tls/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/tls", 0xffb76808)          = -1 ENOENT (No such file or directory)
open("/lib/i686/sse2/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/i686/sse2", 0xffb76808)    = -1 ENOENT (No such file or directory)
open("/lib/i686/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/i686", 0xffb76808)         = -1 ENOENT (No such file or directory)
open("/lib/sse2/libcrypt.so.1", O_RDONLY) = -1 ENOENT (No such file or directory)
stat64("/lib/sse2", 0xffb76808)         = -1 ENOENT (No such file or directory)
stat64("/sbin/sed", 0xffb75900)         = -1 ENOENT (No such file or directory)
stat64("/sbin/mv", 0xffb759e0)          = -1 ENOENT (No such file or directory)
stat64("/sbin/echo", 0xffb75e00)        = -1 ENOENT (No such file or directory)
stat64("/sbin/ln", 0xffb75b60)          = -1 ENOENT (No such file or directory)
```

Or use

```
/opt/bin/strace /opt/bin/update-alternatives --install /opt/bin/bzip2 bzip2 /opt/bin/bzip2-bzip2 80 &> log.txt
```

To save all `strace` output to `log.txt`, and then grep through it.

**Comment by armando-basile** [comment] 2015-09-04 17:30
https://gist.github.com/armando-basile/d1157cfff8032cf3911e#file-strace-log

**Comment by armando-basile** [comment] 2015-09-04 21:34
BINGOOOO :) seems that problem is ln -sf (-f = --force) parameter into update-alternatives script.
I edited update-alternative and changed from ln -sf to ln -s and it work :)

only problem is that if link already exists you need to rm -rf <symlink>

**Comment by alllexx88** [comment] 2015-09-05 05:31
LOL, I managed to reproduce the problem using Genymotion, nailed it down and wrote almost the same thing (regarding `ln`) like 13h ago, but forgot to press 'Comment' :smile: 
Anyway, thanks for your continuous effort to get Optware-ng to work with android! `ipkg` using `/tmp` is probably a bug, but it's OK, since you're REALLY advised to have writable `/tmp` to run anything UNIX.
I've patched `update-alternatives` to not use `-f` `ln` flag, commit and binaries coming soon

**Comment by alllexx88** [comment] 2015-09-05 05:52
Closing this issue for now until new problems arise

**Closed by alllexx88** 2015-09-05 05:52 UTC
Labels: help wanted

**Comment by alllexx88** [comment] 2015-09-06 22:18
@armando-basile this might be interesting for you: 11a91d3743a3588d53b2b6b0ca4e5fdb21dc19b3
I've built a dropbear version (`dropbear-android` package) that  supports Android Mode and allows password or public key logins on android. See `/opt/etc/init.d/S51dropbear`. If you want to add an OpenSSH public key, add it to `/opt/etc/dropbear/authorized_keys` (don't forget to `chmod 600` on it).

**Comment by alllexx88** [comment] 2015-09-30 11:32
@armando-basile and anyone with similar issues: [[ARMv7/Intel][Root][Busybox][init.d]Optware-ng: install pre-compiled native packages](http://forum.xda-developers.com/android/development/armv7-intel-optware-ng-install-pre-t3213845) topic on xda-developers may be of interest
